### PR TITLE
CPT support

### PR DESCRIPTION
**Pull request by su**
Relates to #6 
This adds preliminary support for scanning custom post types in addition to a default of pages and posts. It's working for me, and I'm not introducing anything particularly new so much as doing some consolidating/generalizing, but I *am* kind of learning as I go, so standard disclaimers apply.

### CODE REVIEW

**Comment by jlicht** [comment]
Looking good. Can we make the list of post types a multi-select list, rather than depending on the admin to enter the comma-separated machine names?

**Comment by su** [comment]
Agreed. I'd just never looked at querying the post types before, and was just seeing if I could even make this work at first. I'll have a go at it by the weekend.

**Comment by su** [comment]
Sorry I sat on this so long. Stuff kept getting in the way.

Post types are now presented in a multi-select per @jlicht above, with the following few notes:

* I also introduced an array for hard-coded exclusions. It's just one item right now, but figured I might as well build it to grow.
* The excluded type is post revisions. I can't think of any good reason anybody would want to crawl them and it actually seems like it would be an incredibly bad idea as the revisions pile up over time. This is simple enough to undo if someone makes the case. (Or at the very least there's an obvious spot in the code for them to hack it out themselves.)
* It doesn't seem very likely someone would want to crawl nav menu items, but strictly speaking you *can* put arbitrary external URLs in there, so I left them available to choose. If you think they should be excluded, I have no objection.
* I'm also unsure about the Media/attachment post type at this time. There's an option in the media dialog to insert images directly via external URL (ie. hotlink) rather than actually uploading them, but I don't think I've ever actually used the feature so don't yet know how that shows in the db or the the attachment.php template and if that's relevant to Amber, etc.

**Comment by jlicht** [comment]
Should have mentioned this earlier, but can you reroll this pull request against the develop branch, rather than master? To do this you'll need to close this pull request and create a new one, I believe.

(The master branch represents the current 'live' version of the code; the develop branch is where the next version lives). Thanks.

**Comment by su** [comment]
Argh. Wasn't paying attention. Hold, please.

**Pull request closed without merging**
